baseurl:            http://paigebennett.com/
theme:              hugo-incorporated
title:  			Musings on Design

params:
  inc:
    # Blog Information
    title:        "Musings on Design"
    cover_image:  letters.jpg
    logo:         logo_paige.png
    url:          http://paigebennett.com/
    facebook:     paige.bennett
    github:       paigenomadgirl
    twitter:      paigenomadgirl
    about_link:   /about/
    product_link: /blog/
    contact_link: /contact/
    company: 	    Paige Bennett
    portfolio_link: /portfolio/
    linkedin:     paigebennett
  portfolio:
    title:        "My Work"
    subtitle:     "A little of this. A little of that."
  header:
    lead_in:      "I'm a UX Designer and User Researcher"
    heading:      "It's so nice to meet you."
    more_button:  "See More"