baseurl:            http://paigebennett.com/
theme:              hugo-incorporated
title:  			Musings on Design

params:
  inc:
    # Blog Information
    title:        "Musings on Design"
    cover_image:  cover_image.jpg
    logo:         logo_paige.png
    url:          http://paigebennett.com/
    facebook:     paige.bennett
    github:       paigenomadgirl
    twitter:      paigenomadgirl
    about_link:   /about/
    product_link: /blog/
    company: 	    Paige Bennett
    portfolio_link: /portfolio/
