baseurl:            http://paigebennett.com/
theme:              hugo-incorporated
title:  			Musings on Design

params:
  inc:
    # Blog Information
    title:        "Musings on Design"
    cover_image:  letters.jpg
    logo:         logo_paige.png
    url:          http://paigebennett.com/
    facebook:     paige.bennett
    github:       paigenomadgirl
    twitter:      paigenomadgirl
    about_link:   /about/
    product_link: /blog/
    contact_link: /contact/
    company: 	    Paige Bennett
    portfolio_link: /portfolio/
    linkedin:     paigebennett
  portfolio:
    title:        "Portfolio Of Awesome Stuff"
    subtitle:     "Some of my selected works"
  header:
    lead_in:      "I'm a UX Research Designer!"
    heading:      "Check me out!"
    more_button:  "Scroll down..."