baseurl = "http://yourSiteHere"
languageCode = "en-us"
title = "Musings on Design"
coverimage = "blog-cover.jpg"
authortwitter = "paigenomadgirl"
authorfacebook = "https://www.facebook.com/paige.bennett"
authorinstagram = "paigeb"